---
driver:
  name: vagrant

provisioner:
  name: chef_zero
<% if ENV['CHEF_VERSION'] %>
  require_chef_omnibus: <%= ENV['CHEF_VERSION'] %>
<% end %>

verifier:
  name: inspec
  inspec_tests:
    - test/integration/generic

platforms:
  - name: bento/ubuntu-12.04
  - name: bento/ubuntu-14.04
  - name: bento/ubuntu-16.04
  - name: bento/centos-5.11
  - name: bento/centos-6.8
  - name: bento/centos-7.3

suites:
  - name: default
    run_list:
      - recipe[test]
      - recipe[cups]
      - recipe[cups::default_printer]
    attributes:
      dev_mode: true
      cups:
        default_printer: vagrantprinter1
        printers:
        - vagrantprinter1:
            uri: lpd://192.168.10.5
            desc: HP LaserJet 50000
            location: Front Office
        - vagrantprinter2:
            uri: lpd://192.168.10.6
            desc: HP LaserJet 60000
            location: Back Office
  - name: airprint
    run_list:
      - recipe[test]
      - recipe[cups]
      - recipe[cups::default_printer]
      - recipe[cups::airprint]
    attributes:
      dev_mode: true
      cups:
        default_printer: vagrantprinter1
        printers:
        - vagrantprinter1:
            uri: lpd://192.168.10.5
            desc: HP LaserJet 50000
            location: Front Office
        - vagrantprinter2:
            uri: lpd://192.168.10.6
            desc: HP LaserJet 60000
            location: Back Office
